//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apotea_Interview
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderNumber { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int Order_Status { get; set; }
        public int Shipping_MethodId { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Zip_Code { get; set; }
    }
}
